fix generate config file layout and modify item checkbox margin.
fossasia/pslab-android pull request #2124
Opened 2020-08-30 17:54 UTC by CodeWithSouma

## Fix Generate config file layout
* Add weight to devide linear layout horizontal and vertical 
* Add font size of textView 
* Fix margin checkBox Card

2020-08-31 07:58 UTC, CloudyPadmal requested changes
Use `dimens.xml` file without hard-coding values in resource files.

2020-08-31 09:07 UTC, CodeWithSouma commented
@CloudyPadmal 
## fix hard-coding issue
Remove hard-coding value from `activity_create_config.xml` and put into `dimens.xml`

2020-09-09 15:16 UTC, CodeWithSouma commented
> Use `dimens.xml` file without hard-coding values in resource files.

**Sir please checkout i solved this issue**

2020-10-02 07:59 UTC, CloudyPadmal approved these changes

2020-10-02 08:03 UTC, merged