Substitute Travis with Github Actions
fossasia/pslab-android pull request #2149
Opened 2020-12-08 18:29 UTC by CodeWithSouma

@mariobehling  @CloudyPadmal  
## Substitute Travis with Github Actions, #2148 
* remove travis.yml
* add android.yml

2020-12-14 18:13 UTC, CodeWithSouma commented
@CloudyPadmal  sir can you help regarding this problem #2149. how to fix this ...

2020-12-16 09:22 UTC, CloudyPadmal commented
Hello @CodeWithSouma , Travis build is not currently working for the repos.. That's why the build is failing. So just ignore that for now. Let me check the updates you made.

2021-01-04 15:14 UTC, anurag0singh commented
Why was this rejected?

2021-01-04 15:29 UTC, anurag0singh commented
@CloudyPadmal Sir why was the Github CI is rejected in this particular merge request?

2021-01-06 06:52 UTC, CloudyPadmal approved these changes
Looks good to me. Let's go ahead with this and see..

2021-01-06 06:53 UTC, CloudyPadmal commented
@anurag0singh Travis CI has no more free credits to use by the repos. So we are moving to GitHub actions

2021-04-01 07:35 UTC, CloudyPadmal requested changes
Hi @CodeWithSouma ,

In Travis CI build, when a PR is merged into development branch, an APK file is auto generated. Same happens when the development branch is merged to main branch. Shall we add a function like that to GitHub actions?

2021-04-01 16:07 UTC, CodeWithSouma commented
> Hi @CodeWithSouma ,
> 
> In Travis CI build, when a PR is merged into development branch, an APK file is auto generated. Same happens when the development branch is merged to main branch. Shall we add a function like that to GitHub actions?

I am trying to implement that thing

2021-04-01 16:52 UTC, CloudyPadmal commented
@CodeWithSouma Perfect! Thank you..

2021-04-11 18:15 UTC, CodeWithSouma commented
@CloudyPadmal sir, I add the jobs in GitHub actions, an APK file that is auto-generated.

2021-04-22 18:02 UTC, CloudyPadmal requested changes

2021-04-22 18:02 UTC, CloudyPadmal commented on .github/workflows/android.yml
> +          path: app/build/outputs/apk/debug/app-debug.apk
It's not simple as that. We use two build flavours and once built, a script is used to upload the files to apk branch. https://github.com/fossasia/pslab-android/blob/development/.travis.yml#L37

2021-04-22 18:03 UTC, CloudyPadmal commented
Also, can you test the action setup in a demo branch? Then we can see if it's building without any error.

2021-05-12 11:01 UTC, kartikeysaran commented
@CodeWithSouma are you still working on this ?

2021-05-12 11:16 UTC, CodeWithSouma commented
> @CodeWithSouma are you still working on this ?

yes

2021-05-12 11:22 UTC, kartikeysaran commented
> > @CodeWithSouma are you still working on this ?
> 
> yes

Okay ! 🍻

2021-06-04 07:41 UTC, CloudyPadmal approved these changes
I'll merge this and let's move forward with improvements.

2021-06-04 07:41 UTC, merged