Visibility of PSLab-MIC button changes when PSLab device is not found
fossasia/pslab-android pull request #2180
Opened 2021-01-23 10:33 UTC by arpoch

Fixes #2173 

**Changes**: 
 * The visibility of PSLab-MIC button is set to ``` View.Gone ``` when PSLab device is not found.
 
**Screenshot/s for the changes**: 
![Screenshot_20210122-225917_PSLab](https://user-images.githubusercontent.com/60058139/105575620-f3185a80-5d92-11eb-8d4a-9932f853ba1a.jpg)

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 

[app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/5860037/app-fdroid-debug.zip)

2021-01-23 10:59 UTC, asaikarthikeya requested changes
Add spaces between two if loops.

2021-01-23 11:53 UTC, arpoch commented
> 
> 
> Congrats for your first PR. Add spaces between two if loops.

Thanks. I have made the changes you asked.  Can you please tell what does 'No newline at the end of file' means and what changes should I make now ?

2021-01-23 13:41 UTC, asaikarthikeya commented
> > Congrats for your first PR. Add spaces between two if loops.
> 
> Thanks. I have made the changes you asked. Can you please tell what does 'No newline at the end of file' means and what changes should I make now ?

Reason -- Not exactly sure but as per my understanding Generally when working with git or other Linux distros  , They add '\n' at the end of each line by default sometime the miss to add. In this case \n is missing .

Solution - open terminal in your project folder and the checkout to your branch then try git diff --ignore-all-space .Might solve give a try

2021-01-23 13:42 UTC, asaikarthikeya reviewed
Reason -- Not exactly sure but as per my understanding Generally when working with git or other Linux distros , They add '\n' at the end of each line by default sometime the miss to add. In this case \n is missing .

Solution - open terminal in your project folder and the checkout to your branch then try git diff --ignore-all-space .Might solve give a try

2021-04-01 08:13 UTC, CloudyPadmal commented
That was a feature. Change is not necessary.

2021-04-01 08:13 UTC, closed without merging