Improve compass UI
fossasia/pslab-android pull request #2183
Opened 2021-01-23 17:45 UTC by CodeWithSouma

# Impove compass instrument UI
@CloudyPadmal sir, please check this PR

**Changes:**
- Remove unnecessary RelativeLayout and substitute with LinearLayout
- Update compass image 
- fix some margin

**Screenshot/s for the changes**:

![Compass UI improve](https://user-images.githubusercontent.com/38830139/105609516-da7a6580-5dcf-11eb-88bc-88f34f997900.gif)

**APK for testing**: 
[app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/5860655/app-fdroid-debug.zip)

2021-01-28 15:23 UTC, CodeWithSouma commented
@CloudyPadmal  sir, please check this PR.

2021-04-01 08:18 UTC, CloudyPadmal requested changes
Looks nice and good job with LinearLayout. However, the images added count as about 1MB increase in space which was about 70KB earlier. Let's revert the images back.

2021-04-01 15:44 UTC, CodeWithSouma commented
> Looks nice and good job with LinearLayout. However, the images added count as about 1MB increase in space which was about 70KB earlier. Let's revert the images back.

Sir previous image looks back-dated I am trying to reduce the size of the image

2021-04-12 16:33 UTC, CloudyPadmal approved these changes

2021-06-04 07:45 UTC, merged