Replaced getDrawable() with ResourcesCompat.getDrawable()
fossasia/pslab-android pull request #2207
Opened 2021-03-20 13:52 UTC by Abhinavtdk

Fixes #2206 

**Changes**: 
There were many places where getDrawable(int) was used but it was deprecated. I replaced all these cases with ResourcesCompat.getDrawable().  

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[replaced_getDrawable().zip](https://github.com/fossasia/pslab-android/files/6175706/replaced_getDrawable.zip)

2021-03-20 13:54 UTC, Abhinavtdk commented
@CloudyPadmal can you review it

2021-03-20 14:04 UTC, CodeWithSouma requested changes
Is it necessary to change getResources() with ResourcesCompat() ???

2021-03-20 14:19 UTC, Abhinavtdk commented
> Is it necessary to change getResources() with ResourcesCompat() ???

For now, it offers no difference. But, if we want to, we can associate the drawable resource with a particular theme. I just think it's better to use an alternative as the function is deprecated

2021-04-01 08:53 UTC, CloudyPadmal commented
If it's no difference as for now, we can leave it as it is. There are many other things need fixing. May be lets work on those.

2021-04-01 08:53 UTC, closed without merging