Fixed the map marker issue in Compass
fossasia/pslab-android pull request #2327
Opened 2022-03-10 20:06 UTC by apoorva-raj

Fixes #2304 

## Changes 
Map couldn't place the marker overlay due to differences in the JSON array passed for different sensors.

**Checklist**: 
- [x] **No hard coding**: I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files `strings.xml`, `dimens.xml` or `colors.xml`.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **No extra space**: My code does not contain any extra lines or extra spaces than the ones that are necessary.

2022-03-12 11:17 UTC, CloudyPadmal requested changes

2022-03-12 11:17 UTC, CloudyPadmal commented on app/src/main/java/io/pslab/activity/MapsActivity.java
> +            m.setTitle("Data recorded on" + marker.getString("date"));
Please use string resources instead of hardcoded text. Refer to checklist point 1 in PR template.

2022-03-13 18:40 UTC, CloudyPadmal requested changes
Please update your branch. This contains recent content from previous commits. Let's get used to best practices.

2022-03-15 06:08 UTC, apoorva-raj commented
Yup. I even forgot to create a new branch for this PR. I'll raise a new PR properly.

2022-03-15 06:08 UTC, closed without merging